Update cron.yml

diff --git a/.github/workflows/cron.yml b/.github/workflows/cron.yml
--- a/.github/workflows/cron.yml
+++ b/.github/workflows/cron.yml
@@ -21,19 +21,32 @@ jobs:
           # git add .
           # git commit -m "random cron"
           # git push origin master
+      - name: random cron
+        run: |
           # 获取当前cron分钟数
-          current_min=$(sed -nE 's/.*(- cron: )([0-9]+).*/\2/p' .github/workflows/run.yml)
+          current_min=$(sed -nE 's/(- cron: \')([0-9]+).*/\2/p' .github/workflows/run.yml)
+          echo "Current Minute: $current_min"
+          
+          if ! [[ "$current_min" =~ ^[0-9]+$ ]]; then
+            echo "Error: current_min is not an integer."
+            exit 1
+          fi
+          
           # 生成一个与当前分钟数不同的随机数
           new_min=$current_min
           while [ "$new_min" -eq "$current_min" ]; do
             echo "Minutes repeated, continue to random"
             new_min=$((RANDOM % 59))
           done
+          
           # 替换分钟数
-          sed -i -E "s/(- cron: )([0-9]+)( [^[:space:]]+ \* \* \*')/\1$new_min\3/" .github/workflows/run.yml
+          sed -i -E "s/(- cron: ')([0-9]+)( [^[:space:]]+ \* \* \*')/\1$new_min\3/" .github/workflows/run.yml
+          echo "New Minute: $new_min"
+          
           # git commit
           git config user.name github-actions
           git config user.email github-actions@github.com
           git add .
           git commit -m "random cron"
           git push origin master
+          
